src/Accordion.js

Updates AccordionItem to render its inner div with display:none when not active instead of not rendering it at all.

Renders AccordionItem's div with display:none

---

package.json
src/Radio.js
src/Radio.test.js

Tests wouldn't run without that `react-test-utils` package even though it generates a warning. (Might be a we-need-to-bump-`enzyme`-version-soon thing?)
This fixes a bug where a `Radio.Fieldset`, for which both `value` and `defaultValue` are `null`ish, would fail to set the `value` attributes of the contained radio `input`s.

Fix Radio.Fieldset bug, test runner bug, and bump version

---

src/Pagination.js
src/StatelessModal.js

Connects #40 
Connects #60 
Fixes classnames for modals and pagination.
Fixes modal bug (now shows up on example page):

Fixes modal bug by syncing class names

---

docs-src/package.json
docs-src/src/examples/grid/BlockGrids.js.example
docs-src/src/examples/grid/CenteredColumns.js.example
docs-src/src/examples/grid/HorizontalAlignmentOnRow.js.example
docs-src/src/examples/grid/IncompleteRowsWithoutFlexGrid.js.example
docs-src/src/examples/grid/Intro.js.example
docs-src/src/examples/grid/Nesting.js.example
docs-src/src/examples/grid/Offsets.js.example
docs-src/src/examples/grid/RowCollapse.js.example
docs-src/src/examples/grid/Shrink.js.example
docs-src/src/examples/grid/SourceOrderingWithFlexGrid.js.example
docs-src/src/examples/grid/SourceOrderingWithoutFlexGrid.js.example
docs-src/src/examples/grid/VerticalAlignmentOnCol.js.example
docs-src/src/examples/grid/VerticalAlignmentOnRow.js.example
docs-src/src/layouts/index.scss
docs-src/src/pages/components/grid.js
scss/components/_BlockGrid.scss
scss/components/_FlexGrid.scss
scss/components/_Grid.scss
scss/components/_Layout.scss
scss/vars/_colors.scss
src/Row.js

Temp site if you want to play with this in a browser: http://gratis-quill.surge.sh
I cleaned up the grid examples to make sure they all work with our default SCSS. I had to make some tweaks / additions to our grid code from the base SCSS to do it. I also tried to make the examples as clear as possible by removing unneeded markup and changing some of the column labels.

Clean up grid examples

---

.travis.yml
README.md

This makes a change to the Travis-CI config to do the following:
- updates the README to include the npm badge
- testing against the last two LTS versions of Node (current non-lts is at 9)
- automate publishing to npm with tagged releases and only running the deploy on the Node 8 build/test pipeline to avoid having the deployment script run multiple times since our build matrix tests against multiple versions of Node
- `NPM_EMAIL` and `NPM_TOKEN` is already set on the Travis-CI repository settings

Automate NPM Publish

---

src/Form.js

Added a new property `enableMethodOverride` to the form component. When set to `true`, if the Form's submit method is not `get` or `post` (case-insensitive), the actual method is set to `post`, and a hidden input with the name "_method" (can be changed with the prop `methodOverrideInputName`) is added to the beginning of the forum and has its value set to the desired method.
Change suggested by Joel

Added overrideMethod prop to Form component

---

docs-src/src/layouts/index.js
docs-src/src/pages/index.js

In response to Issue #102, I figured that I would go ahead and add links to the GitHub and NPM page to the Header template. Currently bare-bones, but matches the minimally styled Docs page.

Add GitHub and NPM links to docs page

---

docs-src/src/layouts/Navigation.js

Commenting drawer link out in Navigation didn’t work so I removed the link

Removing drawer link from nav

---

docs-src/src/examples/Menu/Horizontal.js.example
docs-src/src/examples/Menu/Nested.js.example
docs-src/src/examples/Menu/Vertical.js.example
docs-src/src/examples/Tabs/Stateful.js.example
src/Menu.js
src/TopBar.js

- removed all inverse props from components
- removed inverse examples
* the only inverse left is the $anchor-color-inverse variable which we use in the navigation-color-mgmt mixin and probably in future components like links in a banner area*

Removed all inverse examples and props in components

---

docs-src/src/examples/Callout.js.example
docs-src/src/layouts/index.js
docs-src/src/pages/components/Drawer.js
scss/components/_Callout.scss
scss/vars/_colors.scss
scss/vars/_rev-settings.scss

- updated default, primary, secondary styles
- added color mgmt mixin for util colors
- added rows/cols for padding
Some style pattern thoughts: We are used to applying a `primary` prop and seeing a component that has the $primary bkgd color. This component deviates from this in that rev-Callout--primary keeps the default callout bkgd color (set in rev-settings) and only adds a dropshadow.
I think in this case it is an acceptable style deviation because 
1. I personally never need a primary-colored callout
2. if you look at the button component as a comparison, .rev-Button--primary is only adding a dropshadow and maintains the default button color (although the default button color *is* $primary).
3. I would like to further separate primary and secondary classes/props from meaning color. …

Callout updates

---

scss/components/_CardLayout.scss

#118 
The issue has been mentioned below (and in many other posts). This issue is closed.
1. IE11 image resizing bug using Cards and Flexbox #10079
[https://github.com/zurb/foundation-sites/issues/10079](url)
Below is a IE11 screenshot.

[CardLayout css modified for image space issue in IE11]

---

README.md

Hey Robert. Was using awesome possum on a Scandy project this weekend and the readme example didn't work for me unless I used 'awesome-possum' as the package name. Forgive the wordy pull request details - I'm quite sure you could have figured this out. Would appreciate any feedback you might offer on this.

updated readme to show awesome-possum instead of possum

---

package.json

Would adding 
`"prepublish": "npm run clean && npm run babel"`
instead of "prepublishOnly" be a good solution?

#158 possible solution, replace prepublishOnly with prepublish

---

README.md

This patch adds a link to sassy-npm-importer in README for the ease of finding it by the readers.
P.S.: This is my first contribution to the repository and I would love to contribute more :rocket:.

Add link to sassy-npm-importer in README

---

scss/components/_DatePicker.scss
src/DatePicker.js
src/DatePicker/DateInputBlock.js

Hello,
#140 
I haven’t found a way to hide the Firefox native date picker calendar. 
[htps://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions#Pseudo-elements_and_pseudo-classes](url)
It seems there isn’t a ::-webkit-calendar-picker-indicator equivalent in Mozilla.
The Firefox calendar shows up on click (with the Chrome version, the calendar appears on clicking on the drop-down calendar arrow). Preventing default behavior onClick seems to be the only way to hide the Firefox calendar popup.

Date picker firefox

---

scss/components/_CardLayout.scss

#176 
@prehnRA I apologize I only saw the open issue tonight, this is due to a change of mine to fix the extra space there is with images in IE11. I will look for a solution on the extra space issue in IE 11.

[reverse min-height for images and IE11]

---

src/CardLayout.js
src/DatePicker.js

* Checks to see if CardLayout has ```getCalendarRef```
* Checks if calendar ref is available inside ```onClickOutside``` function
* Changes event ```@param``` from ```{Object}``` to ```{SyntheticEvent}```
* All tests passing
Apologies for the previous commit, I forgot to run the tests.  
___
Also,
The site is not automatically reloading on changes, I'm using the procedure below which takes some time.
My workflow has been as follows:
1) Save changes
2) ```npm install``` in the root directory
3) ```npm run cache:rebuild```
4) ```npm run develop```
Is this the normal workflow or am I missing a step?

fix: Set conditional so close Datepicker does not effect TimePicker

---

docs-src/src/examples/grid/HorizontalAlignmentOnRow.js.example
docs-src/src/examples/grid/VerticalAlignmentOnCol.js.example
docs-src/src/examples/grid/VerticalAlignmentOnRow.js.example
docs-src/src/layouts/index.scss
package.json
scss/components/_FlexCols.scss
scss/components/_FlexRows.scss
scss/components/_FloatCols.scss
scss/components/_Grid.scss
scss/components/_components.scss
scss/mixins/_flex.scss
src/Col.js
src/Col.test.js
src/Row.js

connects to #217  updates to row and col components
- renamed props so that they more closely match the css properties they represent
- reorganized the row and col and grid css
- removed old foundation classNames (no longer needed)
- removed unused props
- added css for all flex props (some props didn't have css to go along with them)
- fixed the docs src grid styling
**TODO:** @prehnRA 
- row and col components are getting all of the number prop classNames added regardless of the presence of that prop on the component
I'm pretty sure that this is the offending bit of code:
```
NUMBER_PROPS.forEach((name) => {
const value = props[name]
const func = NUMBER_PROPS_TO_CLASS_NAMES[name]
if (value !== null) {
numberClassNames.push(func(value))
}
delete props[name]
})
```

Row col updates

---

src/DatePicker.js

#218 
Getting invalid argument errors on IE11
IE11 throws an error "invalid arguments" when setting an input's type property (not attribute) to a value that it does not support (e.g. date).
In goodDateInput function I replaced element.type="date" by element.setAttribute('type', 'date')

#218 Datepicker not working in IE11

---

docs-src/src/Headers.js
docs-src/src/pages/components/Map/DefaultMap.js
docs-src/src/pages/components/Map/DesignedRetroMap.js
docs-src/src/pages/components/Map/DesignedSilverMap.js
docs-src/src/pages/components/Map/HybridMap.js
docs-src/src/pages/components/Sticky.js

We have some pages with titles that are still too long for Google. We have pages with descriptions that were too short (and not very descriptive). We had a page with a description too long to fit in google. This fixes those miscellaneous technical SEO lints.

chore: Fix meta & title tags for SEO

---

scss/components/_Buttons.scss

connects to #337
- .rev-Buttons in a .rev-ButtonGroup had spacing between them **when used in an actual project** I think this wasn't happening on harmonium.revelry.co possibly because of styles added to the playground?? Can't confirm this.. but I paired with Blaze on a project and saw the issue and tested the fix
- we added font-size: 0 to the .rev-ButtonGroup so that no character spacing gets added between buttons in a buttongroup

button fix

---

docs-src/src/examples/TopBar/TopBar.js.example
docs-src/src/examples/TopBar/TopBarCenter.js.example
docs-src/src/layouts/Navigation.js
docs-src/src/layouts/index.js
docs-src/src/layouts/index.scss
scss/components/_Brand.scss
src/Brand.js
src/Brand.test.js

#241 logo size in topbar component

---

src/MediaUploader.js

Fixes problem where MediaUploader doesn't use `supportedFileTypes` as the accepts prop on the FileUpload component

use prop for accepts

---

src/MediaUploader.js
src/MediaUploader.test.js

Made a change that sets the name of the file input in `MediaUploader` to and empty string when using signed upload. This prevents file from being submitted with form after s3 upload.

FIX - removes file input name when  signed

---

.github/stale.yml

This would enable stalebot to run on this repository. Goal is to help maintain all issues created. We will be using the default settings of 30 days before an issue is marked as stale and 7 days to close the issue.

Enable Stalebot

---

.travis.yml
package.json

Output of the error that this fixes:
```
+npx nyc mocha './src/**/*.test.js' --opts ./mocha.opts
/home/travis/build/revelrylabs/harmonium/node_modules/mocha/node_modules/yargs/yargs.js:1163
else throw err
^
Error: /home/travis/build/revelrylabs/harmonium/src/Accordion.js: You gave us a visitor for the node type "ClassPrivateProperty" but it's not a valid type
```

Resolve test errors

---

docs-src/src/examples/Flash.js.example
scss/components/_Flash.scss
src/Flash.js

connect #418
Description:
- Add dismissible functionality to flash component
- Allow for passing custom close icon
@blazebarsamian  @HauwaAguillard this is branched off of https://github.com/revelrylabs/harmonium/pull/417 and this is to be merged into that

Feature: Add Dismissible state to Flash component

---

docs-src/package.json

This PR removes the symlinking of the harmonium folder. It instead uses npm's `file:` syntax. This should stop the symlink from being removed when installing packages (because npm will handle it) and do things more idiomatically

chore: reference harmonium in docs-src package.json using the file syntax

---

docs-src/package.json
docs-src/src/ExampleSection.js
docs-src/src/layouts/index.scss
docs-src/src/pages/components/DatePicker.js
docs-src/src/pages/components/TimePicker.js

Replace component-playground with react-live. This is made by
FormidableLabs as well and is more supported. And allows for
more customization of layout.

chore: Put React and HTML output into tabs

---

docs-src/src/pages/design-tokens.js

This PR adds documentation examples for several other design tokens.  This PR is connected to [Issue # 486](https://github.com/revelrylabs/harmonium/issues/486).
Border Radius:
Z-Index is just a list of possible values:
Compared to an [example design token page](https://www.lightningdesignsystem.com/design-tokens/), our version of spacing looks different.  I'll address this with Laura/Design on a future ticket.  Spacing:
For Shadows, this page is static in the same way the the [example design token page](https://www.lightningdesignsystem.com/design-tokens/) is.  Shadows:
Font Weights:

Feature - 486 add documentation pages

---

.gitignore
CHANGELOG.md
README.md
build.js
docs-src/src/layouts/index.scss
docs-src/src/pages/index.js
package.json
src/cli/index.js
src/configuration/index.js
src/configuration/styleDictionary.js
src/configuration/test/index.test.js

connects to #489 
- adds a command line client to harmonium to allow for configuring design tokens and creating new template files based on them
- adds `harmonium init` command to create the initial configuration
- adds `harmonium build` command to generate the assets from the configuration
- adds a configuration module to create the configuration programmatically

feature: harmonium cli

---

.gitignore
build.js
design-tokens.config.json
src/configuration/index.js
src/configuration/test/index.test.js

To be used with JS environments. This makes it so users can update the harmonium.config.js values and have those changes apply for both scss and for JavaScript environments. Such as React Native. Or any CSS-in-JS environments

Feature: Add harmoniumDesignTokens.js as output of cli. 

---

.github/workflows/deploy.yml

#673
Removed line of invalid syntax inadvertently left in GH Actions deploy workflow.

#673 Removed Invalid Syntax from GH Actions Deploy Workflow

---

.github/workflows/deploy.yml

https://github.com/revelrylabs/engineering/issues/245
Thought the 8.0.3 tag + a push to master was going to trigger a deploy, but no dice. @grossvogel mentioned tagging being ok deploy conditions to enable the support of multiple versions at once.

Engineering 245 - changed deploy conditions to tag OR push to master
