revelrylabs/harmonium

- docs-src/generate.js
- docs-src/site.scss
- package.json
- scss/Expander.scss
- src/ExpandingCol.example.js
- src/ExpandingCol.js
- src/ExpandingCol.test.js
> Add expanding column component

- docs-src/src/layouts/Navigation.js
- scss/components/_Menu.scss
- scss/components/_TopBar.scss
- scss/components/_components.scss
Demo at: http://gratis-quill.surge.sh
Groups components in categories logically instead of purely putting everything in alphabetical order.
> Group components by category

- docs-src/src/examples/CloseButton.js.example
Connects to #108 
@CheetoMao I'm not sure if I did what you were asking for so let me know if I misunderstood!
Also, I didn't have to make any updates to the close button position because with the padding and flex properties added, the position position was fixed.
> Close button updates

- scss/components/_Accordion.scss
- scss/components/_Tabs.scss
- scss/mixins/_colors.scss
- scss/vars/_rev-settings.scss
- src/Accordion.js
- src/Tabs.js
Connects to #114 
Checked: Safari, Firefox, Chrome, IE11 and edge
**Disabled Styles:**
> Tabs & Accordions Mixin

- docs-src/src/examples/TopBar/TopBar.js.example
- scss/_base.scss
- scss/components/_Buttons.scss
- scss/components/_Checkbox.scss
- scss/components/_Forms.scss
- scss/components/_Pagination.scss
- scss/components/_Radio.scss
- scss/components/_TopBar.scss
- scss/mixins/_colors.scss
- added disabled form styles
- updated disabled button and pagination styles
(all disabled components use the same disabled mixin)
- removed inverse topbars
- removed unneeded mixins
- updated the nav colors mixin (better defaults)
- update the util colors mixin (better math)
> Disabled styles

- docs-src/package.json
> Add gatsby plugin for react 16.0.0+ compatibility

- package.json
- scripts/postinstall.js
connects to #151 
Will have to be tested when publishing
> Compile files in before publishing instead of post installation

- package.json
Fixes https://github.com/facebook/react/issues/12330
> Removes dependency on react-addons-test-utils

- docs-src/src/layouts/Navigation.js
- scss/components/_Loader.scss
> #130 Add link to `<Loader />` in `<Navigation />`; clean up comments

- src/DatePicker/CalendarDay.js
> 182 datepicker calendar buttons bubble to submit form

- docs-src/src/examples/Modal/Stateless.js.example
Issue #191
Issue #119
There are a few issues with the modal:
> [StatelessModal example with close button and open modal]

- docs-src/src/examples/Drawer/Overlay.js.example
- docs-src/src/examples/Drawer/Scroll.js.example
- docs-src/src/examples/StatelessDrawer/Basic.js.example
This is to modify slightly the Drawer examples I had PR a while ago.
1. Drawer Scroll example is modified so that there is an actual need to scroll 
2. Drawer Overlay modified so that it does not overlay on the codeMirror
3. StatelessDrawer modified so that "About item 1" and "About item 2" are bold so that we can see them distinctly
> Drawer example

- src/DatePicker/Calendar.js
I just started reading through the repository and found that my editor was picking up a lot of linting issues, specifically within the DatePicker.  If there is interest in cleaning this up, then I can go ahead and work on getting the other components in line with the linter.
> Lint Calendar component

- .eslintrc
- src/Card.js
- src/CardLayout.js
- src/DatePicker.js
- src/DatePicker/Calendar.js
- src/DatePicker/CalendarDay.js
- src/DatePicker/DateInputBlock.js
Connected to #189 
Commit ```6c0ba72```
* Lints Datepicker and subcomponents
* Edits conflicting linting rules in .eslintrc
* Uses inline comments to disable ```complexity``` eslint rule
Commit ```a07bc4c```
* Connected to  #189
> Close date picker

- docs-src/src/pages/components/ExpandingCol.js
Hello - fixed a quick typo! fixes #208
> fix typo in expanding col

- docs-src/src/examples/Tabs/Stateful.js.example
- docs-src/src/examples/Tabs/Stateless.js.example
Connects to #115 
(whoops forgot to change my branch!)
> Adding sub-titles for tabs examples

- src/TimePicker/TimeInput.js
> define name from props object

- docs-src/src/layouts/index.scss
- scss/vars/_possum-defaults.scss
> 216 update font family

- scss/components/_FlexRows.scss
> Fix misspellings

- .gitignore
- .npmignore
- package.json
- sass-test/input.scss
> Test sass build

- src/Button.js
- src/Button.test.js
connects to #318 
* fixes a bug in the `Button` component where the `disabled` prop does not get passed through to the html button
> fix disabled button bug

- scss/components/_Sticky.scss
connects to #226 
I've added basic styles, but the sticky component has bugs. Please see #236
> Added very basic styles

- README.md
> Link LICENSE in README.md

- scss/vars/_harmonium-defaults.scss
#346 
fix: added !default for breakpoints list in harmonium-settings.scss
> added missing !default

- docs-src/src/examples/Slider.js.example
- docs-src/src/pages/components/SliderTables/SliderProps.js
- src/Slider.js
extracted and destructured props passed to range input
added step as a prop for slider with default value of 1
> #336 Slider component should have all the available features of HTML input[type="range"]

- scss/components/_Buttons.scss
Connect #395 
- updated hover, focus and active styles for inverted buttons
> inverted button improvements

- README.md
- Please title your PR with: 
- `chore:` if your change only impacts developers and doesn't need to make a new package version
- `fix:` if you change is a bug fix which all users should receive
- `feature:` if your change adds new features or new components
- `BREAKING CHANGE:` if you change changing the API or behavior of the library is a way that breaks some projects
For more details, check out [Conventional Commits](https://www.conventionalcommits.org/).
> docs: updating some grammar in the README

- docs-src/package.json
- docs-src/src/ExampleSection.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/components/DatePicker.js
- docs-src/src/pages/components/TimePicker.js
> chore: Html previews

- docs-src/.babelrc
- docs-src/package.json
- docs-src/src/ExampleSection.js
- docs-src/src/layouts/index.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/components/DatePicker.js
- docs-src/src/pages/components/TimePicker.js
- docs-src/src/pages/index.js
- scss/partials/_typography.scss
* Add more info for using Harmonium with React
* Add info on using Harmonium without React
* Update Layout so that Helmet component isn't needed in child
components to add description
> chore: Update installation and usage instructions

- docs-src/src/pages/index.js
> chore: link to revelry on docs homepage

- docs-src/src/examples/LayoutExamples/LogIn.js.example
- docs-src/src/layouts/Navigation.js
- docs-src/src/pages/components/LayoutExamples/LogIn.js
Connects to #518 
- Please title your PR with: 
- `chore:` if your change only impacts developers and doesn't need to make a new package version
- `fix:` if you change is a bug fix which all users should receive
- `feature:` if your change adds new features or new components
- `BREAKING CHANGE:` if you change changing the API or behavior of the library is a way that breaks some projects
For more details, check out [Conventional Commits](https://www.conventionalcommits.org/).
> feature: 518 login form example

- docs-src/src/examples/LayoutExamples/LandingHero.js.example
- docs-src/src/layouts/Navigation.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/components/LayoutExamples/Landing.js
- scss/app.scss
- scss/templates/_hero.scss
- scss/templates/_templates.scss
- scss/vars/_harmonium-defaults.scss
- settings-templates/_harmonium-component-settings.scss
Connects to #514 
- Please title your PR with: 
- `chore:` if your change only impacts developers and doesn't need to make a new package version
- `fix:` if you change is a bug fix which all users should receive
- `feature:` if your change adds new features or new components
- `BREAKING CHANGE:` if you change changing the API or behavior of the library is a way that breaks some projects
For more details, check out [Conventional Commits](https://www.conventionalcommits.org/).
> feature: add landing hero example

- docs-src/src/examples/LayoutExamples/Pricing.js.example
- docs-src/src/layouts/Navigation.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/components/LayoutExamples/Pricing.js
- scss/base/_layout.scss
- scss/components/_Buttons.scss
- scss/components/_Card.scss
- scss/components/_Lists.scss
- scss/components/_Sections.scss
- scss/templates/_pricing.scss
- scss/templates/index.scss
- scss/utilities/_colors.scss
- scss/utilities/index.scss
connects to #517 
- pricing section example
> 517 pricing page

- docs-src/src/layouts/Navigation.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/design-tokens.js
> chore: Add navigation to the sections of the design token page

- docs-src/src/layouts/Navigation.js
- docs-src/src/layouts/index.scss
- docs-src/src/pages/design-tokens.js
> chore: More tokens in docs

- design-tokens/line-height.json
- docs-src/src/examples/LayoutExamples/LandingHero.js.example
- docs-src/src/layouts/index.scss
- scss/base/_footer.scss
- scss/base/_images.scss
- scss/base/_typography.scss
- scss/base/index.scss
- scss/components/_Brand.scss
- scss/components/_Buttons.scss
- scss/components/_ContentWrapper.scss
- scss/components/_Sections.scss
- scss/components/_TopBar.scss
- scss/templates/_cta.scss
- scss/templates/_featured.scss
- scss/templates/_hero.scss
- settings-templates/_harmonium-component-settings.scss
design bug fixes and updates found while implementing template parts on lintron
- footer styles added
- button vars fix
- rev-content additions 
- rev-section additions
- hero section updates
- header lineheight added to design tokens
- responsive image class updated
> style tweaks

- scss/components/_Forms.scss
fix for form elements inside a container with a text alignment class
> fix: text alignment fix for form elements

- README.md
Documentation for updating to Harmonium 8.0.1
> chore: harmonium 8 in 8 steps

- .github/workflows/test.yml
#673
Ran into one more syntax issue. Duplicate of `673-kickback` branch, only in a different workflow.
> 673 - Removed one more syntax issue
